### ISSUE TITLE
Possible to run the server on Android TV?

### ISSUE THREAD

**Issue by BloodRaven0** [schorschii/RemotePointer-Server#3]
Hey, I'm trying to find a FOSS app that will let me control my Android TV with my Android smartphone via keyboard and touchpad. This app seems to fit the bill perfectly.
Is there a way to run the .jar file for the server on Android TV and would it work as expected?

**Comment by schorschii** [comment]
Unfortunately, there is no way to execute a .jar file on Android and Android TV is currently outside the scope of this project. Android TV has an own protocol for remote controls which is partly [reverse engineered](https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Google-TV-(aka-Android-TV)-Remote-Control-(v2)). If you want to implement this, I'm happy about your pull request, but I currently don't have time for this, sorry.

**Comment by BloodRaven0** [comment]
Thanks for the info!
It's sad that nobody has made a FOSS implementation of this yet. Sadly I'm not a programmer so I can't be of any help there.
Seems like I'll have to use Goolag services then :/
