### ISSUE TITLE
Mouse Pointer Range

### ISSUE THREAD

**Issue by jold42** [schorschii/RemotePointer-Server#6]
I have multiple monitors on Fedora 39.
The remote pointer only covers the top left monitor, a few lines on the monitor directly below and will appear at the edge of the monitor below right. (there is no top right monitor)
I use 5 monitors in total - something like this.

  | one |           |  four  |
|   two    | three |     |five|

hopefully it's just two constants to change 

I like the idea of controlling |five| without cluttering that bench with mouse and keyboard.

**Comment by schorschii** [comment]
Can you please check if it works with the code on the current master branch?

**Comment by jold42** [comment]
Guessing I need to compile / build to try the master branch (I just used your jar file) I see no obvious build instructions
do I need a particular javac ? I see you removed a boundary so looks hopeful!

**Comment by schorschii** [comment]
I created a new beta release. Please test the .jar file from this release.

**Comment by jold42** [comment]
That seems to work fine now - Many thanks indeed
